name: Release

on:
  push:
    branches:
      - main
  # workflow_run:
  #   workflows:
  #     - Test
  #   types:
  #     - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-dependencies
        with:
          node-version: '18.x'

      - name: Check if there are changesets
        run: pnpm changeset status --since=main

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
